### PR TITLE
Issue/95

### LINKED ISSUE #95: Failing to register module must not result in partially installed module
Currently, if an error occurs during registering of a module, the module still is partially installed (it gets a database entry in the table module), while not saving the parts added in onRegister. This makes manual intervention necessary.

### PR DESCRIPTION
**Pull request by Vassyli**
Fixes #95

### CODE REVIEW

File: src/ModuleManager.php [hunk 1]
```diff
@@ -77,8 +74,14 @@ public function register(LibraryConfiguration $library)
...
             // Run the module's onRegister handler.
             $this->g->getLogger()->debug("Calling {$class}::onRegister");
-            $class::onRegister($this->g, $m);
-            $m->save($this->g->getEntityManager());
+
+            try {
+                $class::onRegister($this->g, $m);
+                $m->save($this->g->getEntityManager());
+            } catch (Throwable $e) {
+                $this->g->getLogger()->debug("Calling {$class}::onRegister failed with exception: {$e->getMessage()}");
```
Comment (austenmc) [inline src/ModuleManager.php]: Change this to `getLogger()->error(...)`

**Review by austenmc — APPROVED** [review]
Looks good. Minor nit about log message.
