### PR TITLE
Fix/issue 93

### LINKED ISSUE #93: TimeKeeper->isNewDay checks for null argument which is not allowed by type hint
```
    public function isNewDay(DateTime $lastInteractionTime): bool
    {
        if ($lastInteractionTime == null) {
            return true;
        }
        $t1 = $this->gameTime();
        $t2 = $this->convertToGameTime($lastInteractionTime);
        $d1 = $t1->format("Y-m-d");
        $d2 = $t2->format("Y-m-d");
        return $d1 != $d2;
    }
```
$lastInteractionTime cannot be null, yet the function checks for this value.
Suggested fix: Change `DateTime` to `?DateTime`.

### PR DESCRIPTION
**Pull request by Vassyli**
Fixes #93 and adds a adjust a few minorities.

### CODE REVIEW

File: src/TimeKeeper.php [hunk 1]
```diff
@@ -31,29 +34,50 @@ class TimeKeeper
     public function __construct(DateTime $gameEpoch, int $gameOffsetSeconds, int $gameDaysPerDay)
     {
         $gameEpochCopy = clone($gameEpoch);
-        $this->adjustedEpoch = $gameEpochCopy->add(
-            $this->interval(0, 0, 0, 0, $gameOffsetSeconds)
-        );
+
+        if ($gameOffsetSeconds < 0) {
```
Comment (austenmc) [inline src/TimeKeeper.php:43]: Should this be supported? What's the user's expectation when providing a negative offset? It seems that a negative offset has no effect which is odd. I would prefer it throw an exception if its not going to do anything substantive.

File: src/TimeKeeper.php [hunk 2]
```diff
@@ -31,29 +34,50 @@ class TimeKeeper
...
+            $this->adjustedEpoch = $gameEpochCopy->sub(
+                $this->interval(0, 0, 0, 0, $gameOffsetSeconds*-1)
```
Comment (austenmc) [inline src/TimeKeeper.php:45]: Can we just use `abs()` instead?

**Review by austenmc — CHANGES_REQUESTED** [review]
I see where you're getting to here: you dont want the game time to be constantly advancing, like within the same scene being generated.

Not sure I like this approach though, since this is basically global state for the game, so anyone calling setNow() will affect other gameTime() users.

The time is really local to the viewpoint. Can we add a property to the `Viewpoint` that is `gameTime` or `now` and have scenes use that and leave `TimeKeeper->gameTime()` as an absolute measure? Maybe put in a warning in the comment? :)

File: src/TimeKeeper.php (hunk 1 above)
Comment (Vassyli) [reply src/TimeKeeper.php:43]: User's expectation: If new day happens to be at 1 o'clock, I should set it of by -1 hour instead of +5 hours.

So far this has been "undefined" behaviour: It has not been checked and thus resulted in a parse error from \DateTimeInterval due to the string being "PT-1S" which is not valid.

File: src/TimeKeeper.php (hunk 2 above)
Comment (Vassyli) [reply src/TimeKeeper.php:45]: Sure.

**Comment by Vassyli** [comment]
> Not sure I like this approach though, since this is basically global state for the game, so anyone calling setNow() will affect other gameTime() users.
> The time is really local to the viewpoint. Can we add a property to the Viewpoint that is gameTime or now and have scenes use that and leave TimeKeeper->gameTime() as an absolute measure? Maybe put in a warning in the comment? :)

Can you think of any use of gameTime besides in scene rendering?

Right now, TimeKeeper() keeps giving a totally different time every time getGameTime() is used which is not what I expect. Furthermore, isNewDay() uses getGameTime() internally, thus making the result of isNewDay() dependent in the exact time it's run in the code. Providing an additional argument in isNewDay() might solve this issue but this defeats the purpose of having a "TimeKeeper" at all. Currently, TimeKeeper is not keeping the time, but measuring it regularly. If you want to another time point you can easily use convertToGameTime().

I see the issue with using setNow() though with changing the global state (I introduced this mainly for testing reasons). How about using a constructor argument instead, thus setting the global state for TimeKeeper in stone for the full game?

**Comment by austenmc** [comment]
Yes constructor argument makes sense. Let's do that.

**Comment by Vassyli** [comment]
Updated PR to implement the changes.

**Review by austenmc — APPROVED** [review]
